# Challenge
> Brazilian E-Commerce Public Dataset by Olist
Welcome! This is a Brazilian ecommerce public dataset of orders made at Olist Store. The dataset has information of 100k orders from 2016 to 2018 made at multiple marketplaces in Brazil. Its 21 supportive features allows viewing an order from multiple dimensions: from order status, price and freight performance to customer location, product attributes and finally reviews written by customers.
We also released a geolocation dataset that relates Brazilian zip codes to lat/lng coordinates and a dataset with the payment methods chosen at each order.
This is real commercial data, it has been anonymised, and references to the companies and partners in the review text have been replaced with the names of Game of Thrones great houses.

Link: https://www.kaggle.com/olistbr/brazilian-ecommerce/home

In [10]:
# !pip install kaggle
!kaggle datasets download -d olistbr/brazilian-ecommerce
# export KAGGLE_USERNAME=tbuzze
#!export KAGGLE_KEY=b
#!kaggle datasets [-h]

Warning: Your Kaggle API key is readable by otherusers on this system! To fix this, you can run'chmod 600 /Users/brunoangius/.kaggle/kaggle.json'
Downloading brazilian-ecommerce.zip to /Users/brunoangius/Documents/GitHub/tera-datascience-out2018/12-projects-exploratory-analysis
 98%|█████████████████████████████████████▍| 30.0M/30.5M [00:01<00:00, 24.0MB/s]
100%|██████████████████████████████████████| 30.5M/30.5M [00:01<00:00, 24.5MB/s]

In [2]:
!pip install zip

Collecting zip
  Using cached https://files.pythonhosted.org/packages/dd/31/1c0dc71cd947a5c48f18b0ff9d8fd3a0da0bad9fa63c36dfd9715676926d/zip-0.0.2.tar.gz
Collecting Flask-Admin>=1.0.4 (from zip)
  Using cached https://files.pythonhosted.org/packages/ef/2a/c3f081310e22443ee3bd69b09ee710d208285e4c4b44a5812fe2d8465a92/Flask-Admin-1.5.2.tar.gz
Collecting Flask-Bootstrap>=2.2.2-1 (from zip)
  Using cached https://files.pythonhosted.org/packages/88/53/958ce7c2aa26280b7fd7f3eecbf13053f1302ee2acb1db58ef32e1c23c2a/Flask-Bootstrap-3.3.7.1.tar.gz
Collecting Flask-Cache>=0.10.1 (from zip)
  Using cached https://files.pythonhosted.org/packages/91/c4/f71095437bd4b691c63f240e72a20c57e2c216085cbc271f79665885d3da/Flask-Cache-0.13.1.tar.gz
Collecting Flask-FlatPages>=0.3 (from zip)
  Using cached https://files.pythonhosted.org/packages/90/e5/a5f0b2a64fcf34981ccc01f850a2dbb1f7950b7a976b28a932a4071edddb/Flask_FlatPages-0.7.0-py2.py3-none-any.whl
Collecting Flask-Gravatar>=0.2.4 (from zip)
  Using cached https://files.pythonhosted.org/packages/58/4a/b20260e8d383d0037f2791dd8a3f3ea729ca9f02d7638677a34a236a8702/Flask_Gravatar-0.5.0-py2.py3-none-any.whl
Collecting Flask-Login>=0.1.3 (from zip)
  Using cached https://files.pythonhosted.org/packages/c1/ff/bd9a4d2d81bf0c07d9e53e8cd3d675c56553719bbefd372df69bf1b3c1e4/Flask-Login-0.4.1.tar.gz
Collecting Flask-Mail>=0.7.4 (from zip)
  Using cached https://files.pythonhosted.org/packages/05/2f/6a545452040c2556559779db87148d2a85e78a26f90326647b51dc5e81e9/Flask-Mail-0.9.1.tar.gz
Collecting Flask-PyMongo>=0.2.1 (from zip)
  Using cached https://files.pythonhosted.org/packages/ce/67/1d9c6d6c713aa78f465bdfda071aef58cba26e3fbdb033c9c5b2f234fa38/Flask_PyMongo-2.1.0-py2.py3-none-any.whl
Collecting Flask-Restless>=0.9.1 (from zip)
  Using cached https://files.pythonhosted.org/packages/ae/ad/14eee74ef110f2bd8641de98675037f037dd06d614f7c435671be66a55c7/Flask-Restless-0.17.0.tar.gz
Collecting Flask-SQLAlchemy>=0.16 (from zip)
  Using cached https://files.pythonhosted.org/packages/a1/44/294fb7f6bf49cc7224417cd0637018db9fee0729b4fe166e43e2bbb1f1c8/Flask_SQLAlchemy-2.3.2-py2.py3-none-any.whl
Collecting Flask-Themes>=0.1.3 (from zip)
  Using cached https://files.pythonhosted.org/packages/1a/12/5be3cc2a56c63277177a7e3db4a8f346b9f68a6641277bb3029d401688e3/Flask-Themes-0.1.3.tar.gz
Collecting Flask-Uploads>=0.1.3 (from zip)
  Using cached https://files.pythonhosted.org/packages/c9/a8/2c8e9ec04267d94b7852a374cebeb9a32d60f8cba83818af960e64fafbec/Flask-Uploads-0.2.1.tar.gz
Collecting Flask-WTF>=0.8.2 (from zip)
  Using cached https://files.pythonhosted.org/packages/60/3a/58c629472d10539ae5167dc7c1fecfa95dd7d0b7864623931e3776438a24/Flask_WTF-0.14.2-py2.py3-none-any.whl
Collecting Flask>=0.9 (from zip)
  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
Collecting frozen-flask (from zip)
  Using cached https://files.pythonhosted.org/packages/94/f7/d04d4ee76a9ceb4c1dc1846e86d8784b72e38179fd5f468b61e77bb52296/Frozen_Flask-0.15-py2.py3-none-any.whl
Requirement already satisfied: Jinja2>=2.6 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from zip) (2.10)
Requirement already satisfied: Markdown>=2.2.1 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from zip) (3.0.1)
Requirement already satisfied: PyYAML>=3.11 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from zip) (3.13)
Collecting SQLAlchemy>=0.8.0b2 (from zip)
  Using cached https://files.pythonhosted.org/packages/25/c9/b0552098cee325425a61efdf380c51b5c721e459081c85bbb860f501c091/SQLAlchemy-1.2.12.tar.gz
Collecting Sphinx>=1.3.1 (from zip)
  Using cached https://files.pythonhosted.org/packages/35/e0/e9e83b244eaa382ba21896dda6172617e47aff0be225eb72782cca105d3c/Sphinx-1.8.1-py2.py3-none-any.whl
Collecting WTForms>=1.0.3 (from zip)
  Using cached https://files.pythonhosted.org/packages/9f/c8/dac5dce9908df1d9d48ec0e26e2a250839fa36ea2c602cc4f85ccfeb5c65/WTForms-2.2.1-py2.py3-none-any.whl
Requirement already satisfied: Werkzeug>=0.8.3 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from zip) (0.14.1)
Collecting argparse>=1.2.1 (from zip)
  Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting blinker>=1.2 (from zip)
  Using cached https://files.pythonhosted.org/packages/1b/51/e2a9f3b757eb802f61dc1f2b09c8c99f6eb01cf06416c0671253536517b6/blinker-1.4.tar.gz
Collecting bumpversion>=0.5.3 (from zip)
  Using cached https://files.pythonhosted.org/packages/ad/34/49c914829066558ebd405a56647d3ee26856282b8b8c4cd2c0c8de40ff8e/bumpversion-0.5.3-py2.py3-none-any.whl
Collecting click>=6.3 (from zip)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting colorama>=0.3.7 (from zip)
  Using cached https://files.pythonhosted.org/packages/0a/93/6e8289231675d561d476d656c2ee3a868c1cca207e16c118d4503b25e2bf/colorama-0.4.0-py2.py3-none-any.whl
Collecting coverage>=4.0 (from zip)
  Using cached https://files.pythonhosted.org/packages/a3/7e/c94c21d643bfe7017615994df7b52292a33c8dcf36a6f694af110594edba/coverage-4.5.1-cp36-cp36m-macosx_10_12_x86_64.whl
Requirement already satisfied: cryptography>=1.0.1 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from zip) (2.3.1)
Collecting flake8>=2.4.1 (from zip)
  Using cached https://files.pythonhosted.org/packages/34/a6/49e2849a0e5464e1b5d621f63bc8453066f0f367bb3b744a33fca0bc1ddd/flake8-3.6.0-py2.py3-none-any.whl
Requirement already satisfied: networkx>=1.11 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from zip) (2.2)
Collecting pymongo>=2.5.1 (from zip)
  Using cached https://files.pythonhosted.org/packages/b6/89/f489ad916e8543c976b67d99a46c4bd7e72bf59c3afb323703fe369332bd/pymongo-3.7.2-cp36-cp36m-macosx_10_9_x86_64.whl
Collecting pytest>=2.8.3 (from zip)
  Using cached https://files.pythonhosted.org/packages/02/75/d041ed00994fbac4c5183e6f4bf6c906506bef8da7a57ef3fc825f171020/pytest-3.9.3-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil>=1.5 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from zip) (2.7.3)
Requirement already satisfied: six>=1.10.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from zip) (1.11.0)
Collecting tox>=2.1.1 (from zip)
  Using cached https://files.pythonhosted.org/packages/8f/c3/64bade66e6188a0dc02689392d5c782a9eb6648b54ddc2db034aa495b6a2/tox-3.5.2-py2.py3-none-any.whl
Collecting watchdog>=0.8.3 (from zip)
  Using cached https://files.pythonhosted.org/packages/bb/e3/5a55d48a29300160779f0a0d2776d17c1b762a2039b36de528b093b87d5b/watchdog-0.9.0.tar.gz
Requirement already satisfied: wheel>=0.23.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from zip) (0.32.1)
Collecting wsgiref>=0.1.2 (from zip)
  Using cached https://files.pythonhosted.org/packages/41/9e/309259ce8dff8c596e8c26df86dbc4e848b9249fd36797fd60be456f03fc/wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vn/d9y250hs1v1ckl2f_r2qgy780000gn/T/pip-install-ras9rx2k/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/private/var/folders/vn/d9y250hs1v1ckl2f_r2qgy780000gn/T/pip-install-ras9rx2k/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vn/d9y250hs1v1ckl2f_r2qgy780000gn/T/pip-install-ras9rx2k/wsgiref/

In [11]:
#-- importando biblioteca para leitura do arquivo zip
import zipfile

In [10]:
!pip install --upgrade pip

Collecting pip
  Downloading https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 584kB/s ta 0:00:011
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
Successfully installed pip-18.1

In [4]:
!pip install os-win

Collecting os-win
  Using cached https://files.pythonhosted.org/packages/50/2c/ca05c43dad3c9e57d0c2400f5786a7bdd6935a5e3e190eb4d0361edfe6bd/os_win-4.1.0-py2.py3-none-any.whl
Requirement already satisfied: oslo.log>=3.36.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from os-win) (3.40.1)
Collecting eventlet!=0.18.3,!=0.20.1,>=0.18.2 (from os-win)
  Using cached https://files.pythonhosted.org/packages/86/7e/96e1412f96eeb2f2eca9342dcc4d5bc9305880a448b603b0a8e54439b71c/eventlet-0.24.1-py2.py3-none-any.whl
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from os-win) (5.1.0)
Requirement already satisfied: oslo.config>=5.2.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from os-win) (6.6.2)
Requirement already satisfied: oslo.i18n>=3.15.3 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from os-win) (3.22.1)
Requirement already satisfied: oslo.concurrency>=3.26.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from os-win) (3.28.1)
Requirement already satisfied: Babel!=2.4.0,>=2.3.4 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from os-win) (2.6.0)
Requirement already satisfied: oslo.utils>=3.33.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from os-win) (3.37.1)
Requirement already satisfied: python-dateutil>=2.7.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.log>=3.36.0->os-win) (2.7.3)
Requirement already satisfied: debtcollector>=1.19.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.log>=3.36.0->os-win) (1.20.0)
Requirement already satisfied: oslo.serialization>=2.25.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.log>=3.36.0->os-win) (2.28.1)
Requirement already satisfied: monotonic>=1.4 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.log>=3.36.0->os-win) (1.5)
Requirement already satisfied: oslo.context>=2.20.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.log>=3.36.0->os-win) (2.21.0)
Requirement already satisfied: six>=1.11.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.log>=3.36.0->os-win) (1.11.0)
Requirement already satisfied: dnspython>=1.15.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from eventlet!=0.18.3,!=0.20.1,>=0.18.2->os-win) (1.15.0)
Collecting greenlet>=0.3 (from eventlet!=0.18.3,!=0.20.1,>=0.18.2->os-win)
  Using cached https://files.pythonhosted.org/packages/f8/e8/b30ae23b45f69aa3f024b46064c0ac8e5fcb4f22ace0dca8d6f9c8bbe5e7/greenlet-0.4.15.tar.gz
Requirement already satisfied: PyYAML>=3.12 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.config>=5.2.0->os-win) (3.13)
Requirement already satisfied: netaddr>=0.7.18 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.config>=5.2.0->os-win) (0.7.19)
Requirement already satisfied: rfc3986>=0.3.1 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.config>=5.2.0->os-win) (1.1.0)
Requirement already satisfied: requests>=2.18.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.config>=5.2.0->os-win) (2.18.4)
Requirement already satisfied: stevedore>=1.20.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.config>=5.2.0->os-win) (1.30.0)
Requirement already satisfied: fasteners>=0.7.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.concurrency>=3.26.0->os-win) (0.14.1)
Requirement already satisfied: pytz>=0a in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from Babel!=2.4.0,>=2.3.4->os-win) (2018.5)
Requirement already satisfied: netifaces>=0.10.4 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.utils>=3.33.0->os-win) (0.10.7)
Requirement already satisfied: pyparsing>=2.1.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.utils>=3.33.0->os-win) (2.2.2)
Requirement already satisfied: iso8601>=0.1.11 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.utils>=3.33.0->os-win) (0.1.12)
Requirement already satisfied: wrapt>=1.7.0 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from debtcollector>=1.19.0->oslo.log>=3.36.0->os-win) (1.10.11)
Requirement already satisfied: msgpack>=0.5.2 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from oslo.serialization>=2.25.0->oslo.log>=3.36.0->os-win) (0.5.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from requests>=2.18.0->oslo.config>=5.2.0->os-win) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from requests>=2.18.0->oslo.config>=5.2.0->os-win) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from requests>=2.18.0->oslo.config>=5.2.0->os-win) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/envs/tera-out2018/lib/python3.6/site-packages (from requests>=2.18.0->oslo.config>=5.2.0->os-win) (2018.10.15)
Building wheels for collected packages: greenlet
  Running setup.py bdist_wheel for greenlet ... done
  Stored in directory: /Users/brunoangius/Library/Caches/pip/wheels/cc/28/5a/2687513046a61b17dd78be058a43a069c271f5d7b7623f3dfd
Successfully built greenlet
Installing collected packages: greenlet, eventlet, os-win
Successfully installed eventlet-0.24.1 greenlet-0.4.15 os-win-4.1.0

In [12]:
#-- verificando os arquivocs que foram extraídos do zip
import os
arr = os.listdir()
arr

['kaggle.json',
 'README.md',
 'Img',
 '12-projects-exploratory-analysis.ipynb',
 'brazilian-ecommerce.zip',
 '.ipynb_checkpoints']

In [13]:
#-- extraindo os arquivos do arquivo zip
with zipfile.ZipFile('brazilian-ecommerce.zip', 'r') as myzip:
    myzip.extractall()

In [14]:
#-- verificando os arquivocs que foram extraídos do zip
arr = os.listdir()
arr

['olist_public_dataset_v2.csv',
 'product_category_name_translation.csv',
 'payments_olist_public_dataset.csv',
 'kaggle.json',
 'product_measures_olist_public_dataset_.csv',
 'README.md',
 'Img',
 'geolocation_olist_public_dataset.csv',
 'olist_classified_public_dataset.csv',
 '12-projects-exploratory-analysis.ipynb',
 'sellers_olist_public_dataset_.csv',
 'brazilian-ecommerce.zip',
 '.ipynb_checkpoints',
 'olist_public_dataset_v2_customers.csv']

# 1- Carregar as Bibliotecas

> Numpy, pandas, plotly, matplotlib...

In [61]:
import numpy as np
import pandas as pd
import plotly as plt
import matplotlib as mat

# 2- Verificar e Interpretar as variáveis

> Head, dtypes, describe...

<br>
<center>
<img src="https://media1.tenor.com/images/e4848131a1af20a7e1de5e0443afe472/tenor.gif?itemid=4960555" alt="drawing" width="500px"></center>

In [20]:
geo = pd.read_csv("geolocation_olist_public_dataset.csv", sep=',', encoding="ISO-8859-1", decimal=".")
geo.head().T

                         0          1          2          3          4
zip_code_prefix         10         10         10         10         10
city             sao paulo  sao paulo  sao paulo  sao paulo  sao paulo
state                   sp         sp         sp         sp         sp
lat               -23.5478   -23.5461    -23.541   -23.5468   -23.5464
lng               -46.6361   -46.6448   -46.6426   -46.6458   -46.6431

In [21]:
status = pd.read_csv("olist_classified_public_dataset.csv", sep=',', encoding="ISO-8859-1", decimal=".")
status.head().T

,0,1,2,3,4
Unnamed: 0,0,1,2,3,4
id,1,2,3,4,5
order_status,delivered,delivered,delivered,delivered,delivered
order_products_value,89.99,69,99.8,87,99.9
order_freight_value,14.38,15.23,15.86,12.74,17.95
order_items_qty,1,1,2,1,1
order_sellers_qty,1,1,4,1,2
order_purchase_timestamp,2017-08-30 11:41:01.000000,2017-09-26 09:13:36.000000,2018-01-15 15:50:42.000000,2018-02-04 11:16:42.000000,2017-12-07 11:58:42.000000
order_aproved_at,2017-08-30 11:55:08.970352,2017-09-26 09:28:10.922048,2018-01-17 07:29:56.419769,2018-02-06 05:31:50.990164,2017-12-08 02:36:49.587515
order_estimated_delivery_date,2017-09-21 00:00:00.000000,2017-10-24 00:00:00.000000,2018-02-05 00:00:00.000000,2018-03-13 00:00:00.000000,2018-01-03 00:00:00.000000
order_delivered_customer_date,2017-09-08 20:35:27.276847,2017-09-29 21:13:04.984841,2018-01-23 17:51:31.134866,2018-02-20 19:38:06.633080,2017-12-19 22:33:18.952512
customer_city,Belo Horizonte,Pocos de Caldas,Sao Jose dos Campos,Ribeirao Preto,RIO DE JANEIRO
customer_state,MG,MG,SP,SP,RJ
customer_zip_code_prefix,308,377,122,140,205
product_category_name,beleza_saude,brinquedos,ferramentas_jardim,informatica_acessorios,cama_mesa_banho
product_name_lenght,59,50,59,45,60
product_description_lenght,492,679,341,411,189
product_photos_qty,3,4,2,1,1
review_score,5,5,1,4,3
review_comment_title,NaN,NaN,NaN,NaN,NaN
review_comment_message,tudo certo,o produto chegou antes de prazo parabens pela ...,foi adquirido 6 itens desta loja onde atÃ© o m...,achei a entrega um pouco demorada,comprei 02 jogos de lencois de cetim e uma col...
review_creation_date,2017-09-09 00:00:00.000000,2017-09-30 00:00:00.000000,2018-01-24 00:00:00.000000,2018-02-21 00:00:00.000000,2017-12-20 00:00:00.000000
review_answer_timestamp,2017-09-10 03:27:54+00:00,2017-10-03 05:34:20+00:00,2018-02-02 17:42:43+00:00,2018-02-22 02:09:12+00:00,2017-12-23 04:17:03+00:00
votes_before_estimate,0,3,0,0,0
votes_delayed,0,0,0,3,0
votes_low_quality,0,0,0,0,0
votes_return,0,0,0,0,0
votes_not_as_anounced,0,0,0,0,0
votes_partial_delivery,0,0,3,0,3
votes_other_delivery,0,0,0,0,0
votes_other_order,0,0,0,0,0
votes_satisfied,3,0,0,0,0
most_voted_subclass,satisfeito,antes_prazo,entrega_parcial,atrasado,entrega_parcial
most_voted_class,satisfeito_com_pedido,satisfeito_com_pedido,problemas_de_entrega,problemas_de_entrega,problemas_de_entrega

In [22]:
custid = pd.read_csv("olist_public_dataset_v2_customers.csv", sep=',', encoding="ISO-8859-1", decimal=".")
custid.head().T

,0,1,2,3,4
customer_id,0000ca4ff2795842fd6b122c6d974468,00010f206878ba01f199aec4237de72e,00012a2ce6f8dcda20d059ce98491703,000161a058600d5901f007fab4c27140,00017f1d6cce0d56046219a2cfabcbbb
customer_unique_id,ac0e5d7f07043dd32831bdad3b99ad26,4ed24aaed4079fe0661c0e4b3b420dff,7e0e291c0f4fc2d69208954d26ed0586,ff1dcb27ea444eddb94ea5fea77b875c,237130c4b6717031ed62d9d0b16fd94f

In [28]:
df = pd.read_csv("olist_public_dataset_v2.csv", sep=',', encoding="ISO-8859-1", decimal=".")
df.head().T
# df

,0,1,2,3,4
order_id,b95df3cef5297e79ef709ba256518f6f,59af46052a799e80e2f0c665c587731d,a3e6136894621db402a772c6bc72a12a,b675ea5a618922f6e679e30531b8957b,195a8be6794c487fe6cfbb97b7c61902
order_status,delivered,delivered,delivered,delivered,delivered
order_products_value,349.9,15,238.9,29.99,295.99
order_freight_value,13.84,15.1,18,18.23,47.65
order_items_qty,1,1,1,1,1
order_sellers_qty,1,1,1,1,1
order_purchase_timestamp,2017-01-31 17:19:01.000000,2017-09-09 19:52:54.000000,2017-01-30 17:00:09.000000,2018-03-11 18:18:36.000000,2017-04-20 08:01:08.000000
order_aproved_at,2017-02-01 02:41:21.549551,2017-09-10 20:03:31.535281,2017-01-30 17:31:25.438253,2018-03-11 18:30:37.931962,2017-04-25 08:05:40.405383
order_estimated_delivery_date,2017-03-15 00:00:00.000000,2017-10-02 00:00:00.000000,2017-03-07 00:00:00.000000,2018-04-03 00:00:00.000000,2017-05-24 00:00:00.000000
order_delivered_customer_date,2017-02-06 11:04:24.154259,2017-09-13 20:17:41.296915,2017-02-06 15:43:04.758566,2018-04-03 20:36:43.778451,2017-05-04 18:47:45.721758
customer_id,297dcf281305aabfee256d313076af2b,b7563d94162ed0aa3f8d9cada4bcc536,f102cb15ec41ca30fa2902da06495f6b,e33c250311160298e5b457ca52720a35,8a8f7c9a4450f17ba3ee25a5ba821bc7
customer_city,Guaratuba,Uberlandia,Itapevi,Goiania,Recife
customer_state,PR,MG,SP,GO,PE
customer_zip_code_prefix,832,384,66,743,511
product_category_name,beleza_saude,informatica_acessorios,automotivo,cama_mesa_banho,moveis_decoracao
product_name_lenght,51,44,55,55,49
product_description_lenght,625,1428,637,617,558
product_photos_qty,1,2,1,1,2
product_id,6cdd53843498f92890544667809f1595,ae5cad88462eb7b7b61401e31c45618e,0c9ff9d8ed9b9bdd825487b3a66e05f5,ad0a798e7941f3a5a2fb8139cb62ad78,eaf2046d4c87809247a30050ea13df03
review_id,b95df3cef5297e79ef709ba256518f6f,59af46052a799e80e2f0c665c587731d,a3e6136894621db402a772c6bc72a12a,b675ea5a618922f6e679e30531b8957b,195a8be6794c487fe6cfbb97b7c61902
review_score,5,5,5,4,5
review_comment_title,NaN,NaN,NaN,NaN,NaN
review_comment_message,NaN,entrega em 2 dias produto c boa qualidade otim...,produto veio antes do prazo informado muito ob...,NaN,NaN
review_creation_date,2017-02-07 00:00:00.000000,2017-09-14 00:00:00.000000,2017-02-07 00:00:00.000000,2018-04-04 00:00:00.000000,2017-05-05 00:00:00.000000
review_answer_timestamp,2017-02-09 02:37:37+00:00,2017-09-15 03:43:47+00:00,2017-02-10 14:18:53+00:00,2018-04-05 02:52:31+00:00,2017-05-08 15:20:18+00:00

In [45]:
df2= df['product_id'].value_counts().values

In [51]:
df['product2'] = pd.Series(df2)

In [63]:
df.drop(['product2'], axis = 1)

,order_id,order_status,order_products_value,order_freight_value,order_items_qty,order_sellers_qty,order_purchase_timestamp,order_aproved_at,order_estimated_delivery_date,order_delivered_customer_date,...,product_name_lenght,product_description_lenght,product_photos_qty,product_id,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,b95df3cef5297e79ef709ba256518f6f,delivered,349.90,13.84,1,1,2017-01-31 17:19:01.000000,2017-02-01 02:41:21.549551,2017-03-15 00:00:00.000000,2017-02-06 11:04:24.154259,...,51,625,1,6cdd53843498f92890544667809f1595,b95df3cef5297e79ef709ba256518f6f,5,NaN,NaN,2017-02-07 00:00:00.000000,2017-02-09 02:37:37+00:00
1,59af46052a799e80e2f0c665c587731d,delivered,15.00,15.10,1,1,2017-09-09 19:52:54.000000,2017-09-10 20:03:31.535281,2017-10-02 00:00:00.000000,2017-09-13 20:17:41.296915,...,44,1428,2,ae5cad88462eb7b7b61401e31c45618e,59af46052a799e80e2f0c665c587731d,5,NaN,entrega em 2 dias produto c boa qualidade otim...,2017-09-14 00:00:00.000000,2017-09-15 03:43:47+00:00
2,a3e6136894621db402a772c6bc72a12a,delivered,238.90,18.00,1,1,2017-01-30 17:00:09.000000,2017-01-30 17:31:25.438253,2017-03-07 00:00:00.000000,2017-02-06 15:43:04.758566,...,55,637,1,0c9ff9d8ed9b9bdd825487b3a66e05f5,a3e6136894621db402a772c6bc72a12a,5,NaN,produto veio antes do prazo informado muito ob...,2017-02-07 00:00:00.000000,2017-02-10 14:18:53+00:00
3,b675ea5a618922f6e679e30531b8957b,delivered,29.99,18.23,1,1,2018-03-11 18:18:36.000000,2018-03-11 18:30:37.931962,2018-04-03 00:00:00.000000,2018-04-03 20:36:43.778451,...,55,617,1,ad0a798e7941f3a5a2fb8139cb62ad78,b675ea5a618922f6e679e30531b8957b,4,NaN,NaN,2018-04-04 00:00:00.000000,2018-04-05 02:52:31+00:00
4,195a8be6794c487fe6cfbb97b7c61902,delivered,295.99,47.65,1,1,2017-04-20 08:01:08.000000,2017-04-25 08:05:40.405383,2017-05-24 00:00:00.000000,2017-05-04 18:47:45.721758,...,49,558,2,eaf2046d4c87809247a30050ea13df03,195a8be6794c487fe6cfbb97b7c61902,5,NaN,NaN,2017-05-05 00:00:00.000000,2017-05-08 15:20:18+00:00
5,80dbbd6f2282898dbf912a2ec668175f,delivered,160.00,19.00,1,1,2018-04-03 13:25:35.000000,2018-04-03 13:48:55.262983,2018-05-07 00:00:00.000000,2018-04-18 23:22:45.922709,...,48,1422,1,167752e318335bf6bdd6906c4c470266,80dbbd6f2282898dbf912a2ec668175f,4,NaN,chegou bem antes do prazo Ã³timo vendedor,2018-04-19 00:00:00.000000,2018-04-20 12:31:04+00:00
6,0f374228bdae432c9bdda69f21ccd261,delivered,25.00,19.09,1,1,2018-06-11 19:45:54.000000,2018-06-11 20:22:07.752257,2018-07-04 00:00:00.000000,2018-06-29 20:52:35.173465,...,53,369,2,a30ea5a9dbd95db5a674c4beadb4fb0d,0f374228bdae432c9bdda69f21ccd261,3,NaN,gostei do produto,2018-06-30 00:00:00.000000,2018-07-04 01:36:31+00:00
7,d02366be68b26b954269321e475a79fe,delivered,43.30,17.44,2,1,2017-08-27 15:29:59.000000,2017-08-27 15:45:22.034556,2017-09-13 00:00:00.000000,2017-08-30 18:10:20.939031,...,9,380,2,3cb0ece3f5f0b8121a53635c9f783aa5,d02366be68b26b954269321e475a79fe,5,NaN,NaN,2017-08-31 00:00:00.000000,2017-09-12 06:14:48+00:00
8,d42c3af33e0f04b3d5f012b6559e70c9,delivered,89.90,14.80,1,1,2017-03-13 15:43:08.000000,2017-03-13 15:43:08.000000,2017-04-04 00:00:00.000000,2017-03-22 13:08:38.524197,...,54,245,1,99a4788cb24856965c36a24e339b6058,d42c3af33e0f04b3d5f012b6559e70c9,4,NaN,NaN,2017-03-23 00:00:00.000000,2017-03-24 17:26:18+00:00
9,92e9390c69bcb745fe059efdf93cac2a,delivered,40.00,8.88,1,1,2018-05-07 21:13:12.000000,2018-05-07 21:31:19.636651,2018-05-17 00:00:00.000000,2018-05-10 23:25:30.303778,...,46,490,2,c7fd13b5e515bffdab855d0812842edb,92e9390c69bcb745fe059efdf93cac2a,5,NaN,NaN,2018-05-11 00:00:00.000000,2018-05-12 05:40:51+00:00
10,11edf2e8e2e689ab25e609f6a45b5b7a,delivered,119.90,18.09,1,1,2017-06-26 15:01:51.000000,2017-06-26 15:15:15.515975,2017-07-20 00:00:00.000000,2017-07-12 18:03:23.126456,...,57,242,1,386486367c1f9d4f587a8864ccb6902b,11edf2e8e2e689ab25e609f6a45b5b7a,5,NaN,NaN,2017-07-13 00:00:00.000000,2017-07-14 20:31:22+00:00
11,8fe9a9aa8481e4ca00f5b2e2c84bada8,delivered,59.90,29.95,1,1,2017-09-04 11:00:58.000000,2017-09-05 04:44:25.526827,2017-10-10 00:00:00.000000,2017-09-14 19:56:57.345905,...,59,2124,6,439dee65f97bb5e70b021e1e7cf54a5e,8fe9a9aa8481e4ca00f5b2e2c84bada8,1,NaN,NaN,2017-09-15 00:00:00.000000,2017-09-16 04:00:21+00:00
12,9a641b73a061b55f9ff0c8cf68b84f34,delivered,187.00,22.11,1,1,2017-09-28 17:50:50.000000,2017-09-28 18:07:30.270966,2017-10-26 00:00:00.000000,2017-10-09 18:43:13.080913,...,48,591,3,6bc8dadd7731eae110fe2d177361784c,9a641b73a061b55f9ff0c8cf68b84f34,5,NaN,o produto veio certinho muito bem embalado e b...,2017-10-10 00:00:00.000000,2017-10-10 21:25:25+00:00
13,8447ff843b2616c50c0ced28ab1dae03,delivered,219.90,18.79,1,1,2017-12-20 23:45:07.000000,2017-12-22 02:37:45.399886,2018-01-22 00:00:00.000000,2018-01-09 18:14:02.909579,...,42,782,1,7a10781637204d8d10485c71a6108a2e,8447ff843b2616c50c0ced28ab1dae03,4,NaN,NaN,2018-01-10 00:00:00.000000,2018-01-11 12:02:04+00:00
14,23107c65aa1d14522b0df74d7badfeb9,delivered,13.90,10.96,1,1,2017-03-24 14:11:05.000000,2017-03-25 02:10:25.751867,2017-04-12 00:00:00.000000,2017-03-31 13:03:09.132919,...,52,708,1,d9a51912372ce82133d91ad4dccba508,23107c65aa1d14522b0df74d7badfeb9,5,NaN,NaN,2017-04-01 00:00:00.000000,2017-04-10 03:19:05+00:00
15,80aa9c31556571f08988f12dc07476e1,delivered,39.00,18.37,1,1,2018-07-11 11:35:15.000000,2018-07-12 04:10:14.857298,2018-08-09 00:00:00.000000,2018-07-25 21:57:05.735756,...,39,772,1,c6336fa91fbd87c359e44f5dca5a90ed,80aa9c31556571f08988f12dc07476e1,2,NaN,NaN,2018-07-26 00:00:00.000000,2018-07-27 07:29:21+00:00
16,57c4f75f9937aa5eb6da206e2848c250,delivered,59.99,13.44,1,1,2017-05-08 08:55:30.000000,2017-05-09 09:50:28.184961,2017-05-29 00:00:00.000000,2017-05-15 11:26:46.226039,...,56,518,4,6002665d65ee348dcd357c7bb2f080bd,57c4f75f9937aa5eb6da206e2848c250,5,NaN,NaN,2017-05-16 00:00:00.000000,2017-05-17 17:46:44+00:00
17,e98077a0d199a25a40eab3b14cc230d4,delivered,39.99,15.23,1,2,2018-04-17 13:25:36.000000,2018-04-18 13:31:35.349522,2018-05-10 00:00:00.000000,2018-04-27 20:56:32.787589,...,51,405,2,190d9562bfbe9d3ed876c2ac6f2f5894,e98077a0d199a25a40eab3b14cc230d4,5,NaN,NaN,2018-04-28 00:00:00.000000,2018-04-29 21:07:53+00:00
18,3dd7c740e8065e03818d9b5d493e6918,delivered,121.97,23.43,1,1,2018-05-13 21:25:59.000000,2018-05-13 21:35:19.713716,2018-06-01 00:00:00.000000,2018-05-17 20:06:40.919906,...,56,691,1,d5d6b56db7971e5aeb2c676fa9821d65,3dd7c740e8065e03818d9b5d493e6918,5,Vendedor confiÃ¡vel,produtos em perfeitas condiÃ§Ãµes e entrega de...,2018-05-18 00:00:00.000000,2018-05-21 19:59:55+00:00
19,f27f38d32f2a795d070cbcb6aedcf654,delivered,89.90,18.00,1,1,2017-01-30 13:58:09.000000,2017-01-30 14:33:41.666971,2017-03-07 00:00:00.000000,2017-02-08 10:04:29.815356,...,34,558,2,3c1e3596f9f8a0f95827ce1c109c9c0d,f27f38d32f2a795d070cbcb6aedcf654,5,NaN,NaN,2017-02-09 00:00:00.000000,2017-02-12 00:51:24+00:00
20,86757b84a26b96e53be8c8090ae9f96b,delivered,50.00,16.79,1,2,2017-12-12 11:15:32.000000,2017-12-12 11:28:57.228235,2018-01-12 00:00:00.000000,2017-12-19 20:32:50.249268,...,31,218,1,25d33550509ed49bbaa58492c99b1bcc,86757b84a26b96e53be8c8090ae9f96b,2,NaN,veio apenas um produto porÃ©m foi cobrado 2 pr...,2017-12-20 00:00:00.000000,2017-12-21 01:06:57+00:00
21,3f692d33cf43bbbed35f0e84edba7d2e,delivered,119.99,14.60,1,1,2017-02-27 17:23:36.000000,2017-03-03 02:30:18.007764,2017-03-28 00:00:00.000000,2017-03-27 08:46:37.653699,...,61,992,1,bf128711128b70eaa9e07df69e9a75e2,3f692d33cf43bbbed35f0e84edba7d2e,5,NaN,gostei do celular minha mae achou lindo para p...,2017-03-28 00:00:00.000000,2017-04-08 10:46:19+00:00
22,8c153680e982938c987596e7189af4c2,delivered,69.90,42.52,1,1,2018-03-04 20:19:55.000000,2018-03-04 20:30:52.128560,2018-04-16 00:00:00.000000,2018-03-16 21:44:32.787612,...,54,512,1,6bbe55cf8f85c87b6eebb775a53402f4,8c153680e982938c987596e7189af4c2,4,NaN,a mercadoria chegou antes do prazo final recom...,2018-03-17 00:00:00.000000,2018-03-20 04:21:16+00:00
23,21ea7e4d14409db01f3c79aa48b465b9,delivered,85.00,14.34,1,1,2017-12-17 14:48:57.000000,2017-12-19 10:20:44.436702,2018-01-11 00:00:00.000000,2017-12-29 15:52:59.632048,...,53,710,1,024063adde9af865418b7da3dd897b98,21ea7e4d14409db01f3c79aa48b465b9,5,NaN,NaN,2017-12-30 00:00:00.000000,2017-12-30 20:37:27+00:00
24,d141d48c1e3e6fd2b6f1aa3be81335e7,delivered,55.90,15.15,1,1,2017-08-09 16:01:26.000000,2017-08-09 16:23:39.049986,2017-09-04 00:00:00.000000,2017-08-17 17:57:21.471193,...,49,864,4,ac73a545907ecae37cf969833e3a7959,d141d48c1e3e6fd2b6f1aa3be81335e7,5,NaN,NaN,2017-08-18 00:00:00.000000,2017-08-21 18:30:10+00:00
25,60d5461dab300c5e833a29ac2f534ac4,delivered,86.00,11.81,1,1,2017-07-18 21:46:19.000000,2017-07-18 21:55:14.779216,2017-08-09 00:00:00.000000,2017-07-21 21:23:29.213089,...,57,685,1,60c93709754c1b56d6fcc7187a4810f3,60d5461dab300c5e833a29ac2f534ac4,5,NaN,atendimento produto e entrega perfeitos,2017-07-22 00:00:00.000000,2017-07-23 14:45:55+00:00
26,f5691c2b1ca263490374d13d020bd950,delivered,134.90,38.08,1,1,2018-02-24 17:38:14.000000,2018-02-24 17:50:26.304665,2018-03-22 00:00:00.000000,2018-04-23 17:53:25.073050,...,23,1048,4,04f352bc78b371f4392b0077d5648de5,f5691c2b1ca263490374d13d020bd950,1,NaN,o correio ainda nÃ£o fez a entrega to furioso,2018-03-24 00:00:00.000000,2018-03-27 15:40:30+00:00
27,44de0afee520be53cfddd8428eb63160,delivered,44.90,8.47,1,1,2018-08-05 19:26:12.000000,2018-08-05 19:44:24.472750,2018-08-14 00:00:00.000000,2018-08-07 17:12:10.549378,...,59,81,1,bb42f37fc3d9130e4a4339d24a47dd7c,44de0afee520be53cfddd8428eb63160,5,Muito bom,NaN,2018-08-08 00:00:00.000000,2018-08-09 00:14:53+00:00
28,c7701ff98cb125a8c51b3fc06598ff3b,delivered,18.90,24.35,1,1,2017-02-27 12:11:10.000000,2017-02-27 12:32:25.325627,2017-04-03 00:00:00.000000,2017-03-14 15:34:38.303828,...,51,198,5,5d4278a6fe16e63c7ee443bdcf8ee8e1,c7701ff98cb125a8c51b3fc06598ff3b,5,NaN,NaN,2017-03-16 00:00:00.000000,2017-03-16 15:41:30+00:00
29,beaa8b13b17c25ab4cdfea2c79bf2790,delivered,56.99,11.90,1,1,2017-09-08 10:49:49.000000,2017-09-08 11:03:35.525238,2017-10-02 00:00:00.000000,2017-09-14 20:57:33.456640,...,54,1536,2,2028bf1b01cafb2d2b1901fca4083222,beaa8b13b17c25ab4cdfea2c79bf2790,5,NaN,NaN,2017-09-15 00:00:00.000000,2017-09-16 03:41:40+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,02bb6c10f35f656ae182d420bca92e10,delivered,59.90,18.00,1,1,2017-10-21 23:14:48.000000,2017-10-23 10:50:12.002858,2017-12-06 00:00:00.000000,2017-11-03 20:51:45.811530,...,59,254,1,10714d6a49c0af9ccdab2d806887c5f5,02bb6c10f35f656ae182d420bca92e10,5,NaN,entegou muito antes do praso quanto ao produto...,2017-11-04 00:00:00.000000,2017-11-23 14:29:42+00:00
99971,0306b467a7c7d400d265b71cf6608e15,delivered,61.50,13.58,1,1,2018-02-01 11:32:12.000000,2018-02-03 02:53:21.120220,2018-02-23 00:00:00.000000,2018-02-09 16:36:44.365843,...,38,1337,5,72ef87b1953a2844ed089bd6dcf73913,0306b467a7c7d400d265b71cf6608e15,5,NaN,NaN,2018-02-10 00:00:00.000000,2018-02-21 22:20:52+00:00
99972,39b13503bf74cb241771a5bdc7608426,delivered,299.99,12.21,1,4,2018-06-02 12:03:54.000000,2018-06-02 12:15:10.802903,2018-06-28 00:00:00.000000,2018-06-07 14:31:45.214795,...,37,400,1,7e6ca847e12c659931b47b31e99361c6,39b13503bf74cb241771a5bdc7608426,4,NaN,NaN,2018-06-08 00:00:00.000000,2018-06-11 21:13:54+00:00
99973,104134f2b97da9bec403625917712a00,delivered,37.90,9.02,1,1,2018-06-19 09:33:02.000000,2018-06-19 09:58:18.067006,2018-06-29 00:00:00.000000,2018-06-20 17:23:43.683438,...,59,352,3,3918bb60ff48662029ca9f1e1f7b9842,104134f2b97da9bec403625917712a00,5,NaN,NaN,2018-06-21 00:00:00.000000,2018-06-21 23:52:39+00:00
99974,a6fd19a2fda558819200fc25f1e094d6,delivered,39.00,14.52,1,1,2017-03-31 13:56:30.000000,2017-03-31 14:15:09.530856,2017-04-25 00:00:00.000000,2017-04-10 15:47:29.541019,...,59,309,4,fd31b96cfedbb174cc1663e4fd285a11,a6fd19a2fda558819200fc25f1e094d6,5,NaN,gostei muito do produto antendeu totalmente mi...,2017-04-11 00:00:00.000000,2017-04-12 04:32:09+00:00
99975,fb36706fc43483d15e41500578dbfa6b,delivered,50.90,16.12,1,1,2017-07-17 21:39:37.000000,2017-07-17 21:50:13.796873,2017-08-08 00:00:00.000000,2017-08-03 19:47:53.393358,...,60,473,1,9328c3a5c42ae7b32d53e419f9b93d66,fb36706fc43483d15e41500578dbfa6b,4,NaN,NaN,2017-08-04 00:00:00.000000,2017-08-07 02:59:38+00:00
99976,be8407c731b9edb5eb9c986db9278899,delivered,119.00,85.99,1,1,2017-12-05 21:17:51.000000,2017-12-05 21:30:29.369452,2018-01-04 00:00:00.000000,2018-02-06 17:37:02.347367,...,30,764,1,5ccdfc35d9cff8db4fa46b83d5712899,be8407c731b9edb5eb9c986db9278899,3,NaN,jÃ¡ abri outros chamados e a principio a situa...,2018-01-06 00:00:00.000000,2018-01-11 16:42:16+00:00
99977,c097ba1708f952d3c081e4dc6b27148a,delivered,44.90,16.11,1,1,2017-05-17 21:51:30.000000,2017-05-17 22:05:18.020877,2017-06-08 00:00:00.000000,2017-05-28 04:28:52.403587,...,55,781,2,c03d44fcdfabbabd5185c8eb60f77aea,c097ba1708f952d3c081e4dc6b27148a,5,NaN,NaN,2017-05-29 00:00:00.000000,2017-05-29 22:08:18+00:00
99978,22e80cc2d588160023446a6316057e5c,delivered,55.00,9.34,1,1,2018-01-06 13:57:08.000000,2018-01-06 14:07:23.140757,2018-01-24 00:00:00.000000,2018-01-09 17:13:20.860085,...,52,368,2,0654d3c1e3efc7e7cd9dbde9cb743df2,22e80cc2d588160023446a6316057e5c,4,NaN,com o alinhamento eficaz o resultado Ã© rapide...,2018-01-10 00:00:00.000000,2018-01-10 22:47:07+00:00
99979,3ff220e93d03aad9bb6767d90ac0e846,delivered,109.90,17.02,1,1,2018-01-14 22:48:28.000000,2018-01-14 22:59:24.391275,2018-02-07 00:00:00.000000,2018-01-23 18:13:06.730860,...,32,1531,1,6ed0ed10d62b45f3de46933b0b2989a6,3ff220e93d03aad9bb6767d90ac0e846,3,NaN,NaN,2018-01-31 00:00:00.000000,2018-01-31 23:29:46+00:00
99980,004b081f26dd8deb0a6bdb48701cafc3,delivered,73.49,15.26,1,1,2017-11-26 23:39:31.000000,2017-11-26 23:53:27.329456,2017-12-28 00:00:00.000000,2017-12-07 10:48:50.081295,...,59,3939,6,12827caf723c4ff8030d64dcffe3cdab,004b081f26dd8deb0a6bdb48701cafc3,3,NaN,tudo ok,2017-12-08 00:00:00.000000,2017-12-11 04:18:45+00:00
99981,bb89e6c1d3c84fba6112c71045f7d90a,delivered,23.80,8.11,1,1,2017-11-24 15:04:14.000000,2017-11-24 17:17:55.696427,2017-12-08 00:00:00.000000,2017-11-28 16:33:52.878542,...,53,618,1,6a2909ac21d16b721e4795e7e8ff3e68,bb89e6c1d3c84fba6112c71045f7d90a,3,NaN,Ã© um bom produto,2017-11-29 00:00:00.000000,2017-12-05 14:14:49+00:00
99982,517fe5fecaa07d72b46926cbf5fc59b6,delivered,55.90,18.27,1,1,2018-06-02 12:43:06.000000,2018-06-02 12:55:20.755129,2018-07-20 00:00:00.000000,2018-06-18 21:18:25.345848,...,22,1155,1,fc931a514a3e080c336911cccd59145b,517fe5fecaa07d72b46926cbf5fc59b6,5,NaN,NaN,2018-06-19 00:00:00.000000,2018-06-20 03:50:56+00:00
99983,3594036dc631b02c14cd17fd933d3068,delivered,56.99,8.72,1,1,2017-10-17 10:29:28.000000,2017-10-18 02:53:48.317925,2017-10-30 00:00:00.000000,2017-10-26 13:17:43.011085,...,51,999,2,75d6b6963340c6063f7f4cfcccfe6a30,3594036dc631b02c14cd17fd933d3068,5,NaN,realmente o kit Ã© muito bonito e o acabamento...,2017-10-27 00:00:00.000000,2017-10-27 22:34:45+00:00
99984,56d01e37808556640e75a40c8202b0a8,delivered,39.99,13.71,1,1,2018-05-06 15:46:46.000000,2018-05-06 16:13:50.423726,2018-05-30 00:00:00.000000,2018-05-14 18:22:10.340913,...,44,630,1,50e1b118f266b655f613f753914c42db,56d01e37808556640e75a40c8202b0a8,4,NaN,NaN,2018-05-15 00:00:00.000000,2018-05-18 15:20:22+00:00
99985,ccc3a328508fdf0abe34b16a4a50f474,delivered,572.00,64.74,1,1,2017-05-21 11:18:26.000000,2017-05-23 04:22:45.445318,2017-06-14 00:00:00.000000,2017-05-29 10:07:56.690492,...,38,1176,3,5f504b3a1c75b73d6151be81eb05bdc9,ccc3a328508fdf0abe34b16a4a50f474,5,NaN,muito bom comprar nas lojas lannister,2017-05-30 00:00:00.000000,2017-05-31 14:17:13+00:00
99986,f29e1935908b5e7f9e22b36522664b07,delivered,104.90,17.64,1,1,2018-03-12 02:39:09.000000,2018-03-12 03:20:30.901413,2018-04-02 00:00:00.000000,2018-03-17 15:48:37.499874,...,33,1076,3,0a57f7d2c983bcf8188589a5fea4a8da,f29e1935908b5e7f9e22b36522664b07,5,NaN,entregar rÃ¡pida,2018-03-18 00:00:00.000000,2018-03-19 00:01:08+00:00
99987,02b0bf9164ac7753f9880e46dba17f6c,delivered,19.99,20.78,1,2,2017-06-17 17:04:31.000000,2017-06-17 17:15:21.715915,2017-07-07 00:00:00.000000,2017-06-30 12:22:11.055851,...,54,333,4,1a300f482e35d7eac74b229be067aefd,02b0bf9164ac7753f9880e46dba17f6c,5,NaN,NaN,2017-07-01 00:00:00.000000,2017-07-03 13:46:41+00:00
99988,d5da45840715f8327ca0a4d732140175,delivered,46.40,9.37,1,2,2017-03-12 19:27:56.000000,2017-03-12 19:27:56.000000,2017-03-30 00:00:00.000000,2017-03-20 11:33:20.007772,...,43,1539,1,745791131f1438947cfb00c6672ad886,d5da45840715f8327ca0a4d732140175,5,NaN,NaN,2017-03-21 00:00:00.000000,2017-03-22 16:08:36+00:00
99989,045524a5ae6c874b746523a6fd79f4f9,delivered,112.90,13.13,1,1,2017-09-02 18:22:11.000000,2017-09-02 18:30:21.081017,2017-09-21 00:00:00.000000,2017-09-08 22:47:42.763878,...,51,699,10,a9fb80187bf64d19dd2804f25e83c5e6,045524a5ae6c874b746523a6fd79f4f9,5,NaN,NaN,2017-09-09 00:00:00.000000,2017-09-13 00:19:48+00:00
99990,f57b72afcc4b452e33507898aa140ff5,delivered,99.80,41.98,2,1,2018-06-26 13:38:55.000000,2018-06-26 13:56:23.927574,2018-07-17 00:00:00.000000,2018-07-09 13:16:36.750151,...,57,366,2,368c6c730842d78016ad823897a372db,f57b72afcc4b452e33507898aa140ff5,5,NaN,NaN,2018-07-10 00:00:00.000000,2018-07-11 05:31:42+00:00
99991,006e05e81c068ddc38e48ebe189b922e,delivered,29.00,14.10,1,1,2017-12-27 21:50:43.000000,2017-12-27 22:07:25.553896,2018-01-24 00:00:00.000000,2018-01-03 11:14:47.692158,...,55,569,5,02475368dfb38934fe55f574024fe1d7,006e05e81c068ddc38e48ebe189b922e,4,NaN,atendeu minhas expectativas,2018-01-04 00:00:00.000000,2018-01-05 02:02:42+00:00
99992,cef44224a07647470c1afcdbeaa43c92,delivered,45.90,8.72,1,1,2017-05-22 13:14:25.000000,2017-05-22 13:25:15.759119,2017-06-02 00:00:00.000000,2017-05-25 15:57:57.058432,...,35,306,2,6e1e8b68a310487ba64941be76e630ba,cef44224a07647470c1afcdbeaa43c92,5,NaN,NaN,2017-05-26 00:00:00.000000,2017-05-27 06:06:33+00:00
99993,615e54068238441742c4daf6a7b4ccff,invoiced,19.90,11.85,1,1,2017-11-13 16:27:09.000000,2017-11-14 04:26:44.427273,2017-12-01 00:00:00.000000,NaN,...,36,886,2,8b100f92b312e18e03f0ee8f0c0011bd,615e54068238441742c4daf6a7b4ccff,4,NaN,bom produto,2017-11-25 00:00:00.000000,2017-11-25 12:13:20+00:00
99994,e98de168acf11b1a80cea2ad5e8a5c61,delivered,118.90,38.38,1,1,2017-07-06 16:33:09.000000,2017-07-06 16:45:11.484040,2017-08-07 00:00:00.000000,2017-07-24 20:11:53.407990,...,59,946,5,3787e7ea150c3a54578d3f58b133f9bf,e98de168acf11b1a80cea2ad5e8a5c61,4,NaN,o produto comprado demorou demais fiquei irritado,2017-07-25 00:00:00.000000,2017-07-26 07:01:36+00:00
99995,5e0fb4a48b36946c8121f9e03964d9c2,delivered,198.00,91.98,2,1,2017-10-02 20:19:43.000000,2017-10-04 02:43:52.408623,2017-10-31 00:00:00.000000,2017-10-11 16:25:47.945541,...,36,450,1,08574b074924071f4e201e151b152b4e,5e0fb4a48b36946c8121f9e03964d9c2,5,NaN,show,2017-10-12 00:00:00.000000,2017-10-12 19:53:25+00:00
99996,138d22c05c5e456f19bdc7dcf09b89aa,delivered,59.00,11.02,1,1,2017-03-22 06:13:55.000000,2017-03-22 06:13:55.000000,2017-04-10 00:00:00.000000,2017-03-31 13:23:12.316309,...,26,119,1,0cf573090c66bb30ac5e53c82bdb0403,138d22c05c5e456f19bdc7dcf09b89aa,5,NaN,NaN,2017-04-01 00:00:00.000000,2017-04-04 04:42:58+00:00
99997,a97f1478d7e7648bf5bd2af02d1392a7,delivered,119.99,18.09,1,1,2017-06-10 20:12:12.000000,2017-06-10 21:32:48.260831,2017-07-05 00:00:00.000000,2017-06-24 07:26:42.947365,...,42,660,1,14555ba663de8689feacf1d0819cc3b3,a97f1478d7e7648bf5bd2af02d1392a7,5,NaN,recomendo,2017-06-25 00:00:00.000000,2017-06-27 22:11:50+00:00
99998,7212b1926de631a35211dd5b4bd9d77b,delivered,119.99,18.09,1,1,2017-09-12 10:24:08.000000,2017-09-12 10:35:15.542788,2017-10-02 00:00:00.000000,2017-09-19 22:51:55.417806,...,33,659,1,cfd652b39b87b4e06cf4ea106a32db47,7212b1926de631a35211dd5b4bd9d77b,1,NaN,NaN,2017-09-20 00:00:00.000000,2017-09-25 21:22:57+00:00

In [64]:
df.head().T

,0,1,2,3,4
order_id,b95df3cef5297e79ef709ba256518f6f,59af46052a799e80e2f0c665c587731d,a3e6136894621db402a772c6bc72a12a,b675ea5a618922f6e679e30531b8957b,195a8be6794c487fe6cfbb97b7c61902
order_status,delivered,delivered,delivered,delivered,delivered
order_products_value,349.9,15,238.9,29.99,295.99
order_freight_value,13.84,15.1,18,18.23,47.65
order_items_qty,1,1,1,1,1
order_sellers_qty,1,1,1,1,1
order_purchase_timestamp,2017-01-31 17:19:01.000000,2017-09-09 19:52:54.000000,2017-01-30 17:00:09.000000,2018-03-11 18:18:36.000000,2017-04-20 08:01:08.000000
order_aproved_at,2017-02-01 02:41:21.549551,2017-09-10 20:03:31.535281,2017-01-30 17:31:25.438253,2018-03-11 18:30:37.931962,2017-04-25 08:05:40.405383
order_estimated_delivery_date,2017-03-15 00:00:00.000000,2017-10-02 00:00:00.000000,2017-03-07 00:00:00.000000,2018-04-03 00:00:00.000000,2017-05-24 00:00:00.000000
order_delivered_customer_date,2017-02-06 11:04:24.154259,2017-09-13 20:17:41.296915,2017-02-06 15:43:04.758566,2018-04-03 20:36:43.778451,2017-05-04 18:47:45.721758
customer_id,297dcf281305aabfee256d313076af2b,b7563d94162ed0aa3f8d9cada4bcc536,f102cb15ec41ca30fa2902da06495f6b,e33c250311160298e5b457ca52720a35,8a8f7c9a4450f17ba3ee25a5ba821bc7
customer_city,Guaratuba,Uberlandia,Itapevi,Goiania,Recife
customer_state,PR,MG,SP,GO,PE
customer_zip_code_prefix,832,384,66,743,511
product_category_name,beleza_saude,informatica_acessorios,automotivo,cama_mesa_banho,moveis_decoracao
product_name_lenght,51,44,55,55,49
product_description_lenght,625,1428,637,617,558
product_photos_qty,1,2,1,1,2
product_id,6cdd53843498f92890544667809f1595,ae5cad88462eb7b7b61401e31c45618e,0c9ff9d8ed9b9bdd825487b3a66e05f5,ad0a798e7941f3a5a2fb8139cb62ad78,eaf2046d4c87809247a30050ea13df03
review_id,b95df3cef5297e79ef709ba256518f6f,59af46052a799e80e2f0c665c587731d,a3e6136894621db402a772c6bc72a12a,b675ea5a618922f6e679e30531b8957b,195a8be6794c487fe6cfbb97b7c61902
review_score,5,5,5,4,5
review_comment_title,NaN,NaN,NaN,NaN,NaN
review_comment_message,NaN,entrega em 2 dias produto c boa qualidade otim...,produto veio antes do prazo informado muito ob...,NaN,NaN
review_creation_date,2017-02-07 00:00:00.000000,2017-09-14 00:00:00.000000,2017-02-07 00:00:00.000000,2018-04-04 00:00:00.000000,2017-05-05 00:00:00.000000
review_answer_timestamp,2017-02-09 02:37:37+00:00,2017-09-15 03:43:47+00:00,2017-02-10 14:18:53+00:00,2018-04-05 02:52:31+00:00,2017-05-08 15:20:18+00:00
product2,653,615,475,449,435

In [56]:
sell = pd.read_csv("sellers_olist_public_dataset_.csv", sep=',', encoding="ISO-8859-1", decimal=".")
sell.head().T

,0,1,2,3,4
order_id,0faabac07131235fc5d9d711471cb4db,970f41d57d6e21afa7b8c701b09acb95,b674ed44cc3f6a869249421debebe104,cbe9eae36605cf2bd005c6bc1ae5f864,f562f8a4adf5a459176f7170d0da220d
product_id,40b09f33e646d488df2ca6fec4082d50,d1c427060a0f73f6b889a5c7c61f2ac4,bd7cd34fc6d02e730221b11edc354aae,0e95d6eef2bedaf4ecf3c33f78199059,9a3a44b7cc16f2592b2110e4205edf97
seller_id,3d871de0142ce09b7081e2b9d1733cb1,a1043bafd471dff536d0c462352beb48,46dc3b2cc0980fb8ec44634e21d2718e,dc4a0fc896dc34b0d5bfec8438291c80,5a8e7d5003a1f221f9e1d6e411de7c23
seller_zip_code_prefix,132,371,222,149,130
seller_city,campo limpo paulista,ilicinea,rio de janeiro,ibitinga,campinas
seller_state,SP,MG,RJ,SP,SP

In [84]:
dataset = pd.merge(df, sell, how='left', on='order_id')

In [85]:
dataset.shape

(106538, 31)

In [86]:
df.shape

(100000, 26)

In [113]:
# df.groupby(['Fruit','Name']).sum()
# df.groupby(['Name', 'Fruit'])['Number'].agg('sum')
# 
dataset.groupby(['order_id'])['order_products_value'].agg('sum')

order_id
0000f01da58c553799200eb71eb0563b     54.90
00010242fe8c5a6d1ba2dd792cb16214     58.90
00026c8a4fe2c14efa2afe807921981c    389.98
000312d02b605a8a630c3a9882793ffb    600.00
000330af600103828257923c9aa98ae2    118.98
00042b26cf59d7ce69dfabb4e55b4fd9    199.90
00048cc3ae777c65dbb7d2a0634bc1ea     21.90
0004940968b6f9fdb7ef5bb315d3dd45     28.99
0004e45495a3c003903562f035a835ce     89.90
00054e8431b9d7675808bcb819fb4a32     19.90
000576fe39319847cbb9d288c5617fa6    810.00
000600fcb6cd339109fe8f27d7ce7bca     29.99
00063b381e2406b52ad429470734ebd5     45.00
0006ec9db01a64e59a68b2c340bf65a7     74.00
0008288aa423d2a3f00fcb17cd7d8719     99.80
000844e66735b6b771578023091a2a37     69.90
0009792311464db532ff765bf7b182ae     99.90
000a1a23c186e860e31dd744d93f059a     99.90
000a950f6be5856bec0567ebccfa5d54     26.90
000aed2e25dbad2f9ddb70584c5a2ded    144.00
000e8b0af0aac34c2d96d4baf5162ccf     55.90
000ed9901656cc1e7c2f973f8c6e2309     98.90
000f99bb272406acd1dce9b54895dd62     56.97
001021efaa8636c29475e7734483457d     49.00
0010b2e5201cc5f1ae7e9c6cc8f5bd00     48.90
00119ff934e539cf26f92b9ef0cdfed8    219.90
0011d82c4b53e22e84023405fb467e57    289.00
00125cb692d04887809806618a2a145f    109.90
0012c0691fc9e9904585a7982ebc3f3d    120.00
0013503b13da1eac686219390b7d641b    119.90
                                     ...
ffeba575a4bb795de0386cf957b3c6c3     21.00
ffec6450964463cf91dbb7d7ba22b543     24.89
ffed7e90414c1477a6b92554661d465f    149.90
ffeeb911d070bea3dd20bd5fd01da5e8     79.50
ffef5373bf5a7f3209d5330de6253dbb     51.96
ffef98cd5ecdc992fefbd967549520dd    139.90
ffefb169ddf34cecc0622a6d3cc387f8    129.99
fff1e3e76b816bfe8ef16678cc53c643     65.99
fff1fe51c4f9bf5963d6329553269a12    719.88
fff2e9e3aa8644e19710216b4ef53ab2     69.90
fff37e5e209512db4dd1c8a03beed88b     49.89
fff3983dfa3c5a0d752d8d17baa406a0     66.39
fff674501b113ab737d4edc3e9bb44ca     39.90
fff6889749958e42b47a7977a4cf0ea0     92.00
fff6b8ca971f8e3ec822e99d0f2d3d21    199.00
fff70321841e2d34bb629d8f4e9e68c3    105.00
fff7c4452f050315db1b3f24d9df5fcd    736.00
fff81f66a219237ad51e628c210e066e     36.85
fff8287bbae429a99bb7e8c21d151c41    360.00
fff90cdcb3b2e6cfb397d05d562fd3fe     89.90
fff972a570e5ae1752dc1896258a6525    157.00
fff989f6b6cfb906d6c39ed78258ff90     59.00
fffa82886406ccf10c7b4e35c4ff2788    229.90
fffaf8a07a1dfd71f6997e2c694de14b     59.90
fffb0b1a50e65c449020434fa835e078      4.90
fffb9224b6fc7c43ebb0904318b10b5f    220.00
fffc6722901386c66d5f8009639fcb24    169.90
fffe18544ffabc95dfada21779c9644f     55.99
fffe7967a0e803b9331617191f6c7ed7     97.60
ffff4b4f540d2d98fae13222d4d3aec1     38.90
Name: order_products_value, Length: 96264, dtype: float64

In [114]:
dataset.head()

,order_id,order_status,order_products_value,order_freight_value,order_items_qty,order_sellers_qty,order_purchase_timestamp,order_aproved_at,order_estimated_delivery_date,order_delivered_customer_date,...,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product2,product_id_y,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,b95df3cef5297e79ef709ba256518f6f,delivered,349.90,13.84,1,1,2017-01-31 17:19:01.000000,2017-02-01 02:41:21.549551,2017-03-15 00:00:00.000000,2017-02-06 11:04:24.154259,...,NaN,NaN,2017-02-07 00:00:00.000000,2017-02-09 02:37:37+00:00,653.0,6cdd53843498f92890544667809f1595,ccc4bbb5f32a6ab2b7066a4130f114e3,803.0,curitiba,PR
1,59af46052a799e80e2f0c665c587731d,delivered,15.00,15.10,1,1,2017-09-09 19:52:54.000000,2017-09-10 20:03:31.535281,2017-10-02 00:00:00.000000,2017-09-13 20:17:41.296915,...,NaN,entrega em 2 dias produto c boa qualidade otim...,2017-09-14 00:00:00.000000,2017-09-15 03:43:47+00:00,615.0,ae5cad88462eb7b7b61401e31c45618e,ce27a3cc3c8cc1ea79d11e561e9bebb6,30.0,sao paulo,SP
2,a3e6136894621db402a772c6bc72a12a,delivered,238.90,18.00,1,1,2017-01-30 17:00:09.000000,2017-01-30 17:31:25.438253,2017-03-07 00:00:00.000000,2017-02-06 15:43:04.758566,...,NaN,produto veio antes do prazo informado muito ob...,2017-02-07 00:00:00.000000,2017-02-10 14:18:53+00:00,475.0,0c9ff9d8ed9b9bdd825487b3a66e05f5,8581055ce74af1daba164fdbd55a40de,71.0,guarulhos,SP
3,b675ea5a618922f6e679e30531b8957b,delivered,29.99,18.23,1,1,2018-03-11 18:18:36.000000,2018-03-11 18:30:37.931962,2018-04-03 00:00:00.000000,2018-04-03 20:36:43.778451,...,NaN,NaN,2018-04-04 00:00:00.000000,2018-04-05 02:52:31+00:00,449.0,ad0a798e7941f3a5a2fb8139cb62ad78,1835b56ce799e6a4dc4eddc053f04066,149.0,ibitinga,SP
4,195a8be6794c487fe6cfbb97b7c61902,delivered,295.99,47.65,1,1,2017-04-20 08:01:08.000000,2017-04-25 08:05:40.405383,2017-05-24 00:00:00.000000,2017-05-04 18:47:45.721758,...,NaN,NaN,2017-05-05 00:00:00.000000,2017-05-08 15:20:18+00:00,435.0,eaf2046d4c87809247a30050ea13df03,8bd0f31cf0a614c658f6763bd02dea69,12.0,sao paulo,SP

In [118]:
table = pd.pivot_table(dataset, values = 'order_products_value', index='seller_state', columns = 'customer_state', aggfunc=np.mean)

In [119]:
table

customer_state,AC,AL,AM,AP,BA,CE,DF,ES,GO,MA,...,PR,RJ,RN,RO,RR,RS,SC,SE,SP,TO
seller_state,,,,,,,,,,,,,,,,,,,,,
AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.000000,...,NaN,NaN,NaN,319.000000,NaN,NaN,NaN,94.000000,259.000000,NaN
BA,1270.000000,396.828333,1340.000000,813.450000,516.772373,413.315000,715.312143,338.288571,574.440909,648.130556,...,510.560000,419.939014,474.080000,1014.700000,850.000000,1001.080417,753.687500,520.985455,516.786923,179.000000
CE,NaN,214.000000,149.900000,NaN,155.880000,34.273333,234.098000,149.900000,NaN,599.000000,...,158.644000,480.362500,NaN,599.000000,NaN,NaN,311.000000,192.000000,176.800000,NaN
DF,199.000000,168.950000,NaN,NaN,149.546667,118.767692,130.555283,137.216087,120.644211,63.578000,...,141.087692,136.494444,172.800000,NaN,NaN,93.364762,123.476111,119.500000,110.318000,76.947500
ES,NaN,99.000000,NaN,NaN,158.810000,121.998571,152.933333,130.727273,129.333333,95.945000,...,101.290833,124.287368,18.900000,NaN,NaN,127.802917,102.592000,NaN,117.625977,220.000000
GO,86.995000,822.557778,52.900000,NaN,126.087778,127.101111,145.959091,157.832500,118.794348,137.358182,...,78.103889,89.153393,95.900000,108.390000,NaN,90.652143,95.515000,NaN,159.952612,98.500000
MG,195.950000,213.763333,156.744286,114.966667,105.817201,102.991589,129.881364,106.974118,121.332872,111.884096,...,118.975584,119.246501,128.173784,127.035909,42.930000,130.275687,104.020957,103.106410,111.127105,121.845652
MS,369.800000,NaN,NaN,NaN,189.900000,NaN,189.717500,NaN,261.990000,NaN,...,193.945000,191.310000,NaN,NaN,NaN,129.990000,174.900000,NaN,168.969412,NaN
MT,NaN,NaN,51.945000,NaN,133.580000,NaN,148.283333,168.325000,94.109000,138.633333,...,98.198750,154.966667,34.500000,69.612500,169.000000,135.425000,80.673333,NaN,136.551351,NaN
PA,NaN,NaN,NaN,NaN,339.000000,NaN,NaN,NaN,NaN,NaN,...,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,349.000000,137.125000,NaN
PB,NaN,747.250000,NaN,NaN,544.000000,624.745000,278.700000,NaN,NaN,67.900000,...,NaN,434.257143,159.000000,NaN,NaN,NaN,1899.000000,NaN,717.400000,699.500000
PE,34.990000,39.456000,NaN,NaN,53.924000,68.832500,39.900000,57.450000,316.615000,NaN,...,71.190000,77.866667,22.463333,NaN,NaN,612.131667,28.416667,40.000000,137.625833,NaN
PI,NaN,NaN,NaN,NaN,295.000000,295.000000,NaN,NaN,NaN,296.966667,...,NaN,295.000000,NaN,NaN,NaN,295.000000,295.000000,NaN,NaN,NaN
PR,54.450000,385.506545,141.973077,574.588000,202.419144,211.371594,165.624878,154.108088,224.088434,217.513250,...,142.875172,143.336318,224.998636,240.480000,190.280000,141.023437,137.527840,196.948125,144.867871,166.384500
RJ,NaN,123.809091,160.286000,55.000000,201.187377,212.914565,182.643735,160.571310,154.117907,144.288000,...,174.993960,153.444924,151.401176,162.693000,399.990000,158.185000,171.873854,120.860000,167.447222,141.008571
RN,NaN,94.900000,NaN,NaN,241.212500,210.966667,151.200000,NaN,NaN,NaN,...,799.000000,912.633333,33.560976,NaN,NaN,358.160000,NaN,NaN,93.233333,NaN
RO,NaN,NaN,NaN,NaN,279.990000,NaN,119.000000,228.000000,NaN,NaN,...,208.100000,693.323333,NaN,NaN,NaN,374.990000,NaN,NaN,439.480000,NaN
RS,69.945000,212.087778,158.450000,105.000000,237.271111,319.533500,180.753333,128.378485,256.248065,262.899231,...,160.441950,179.791992,76.355000,166.046667,NaN,174.088587,171.622500,334.087778,146.951723,359.323333
SC,337.192500,104.546364,114.912500,123.200000,235.725165,246.671304,120.065000,137.275800,256.566596,157.757059,...,137.684521,139.626853,187.726000,145.937143,NaN,155.476093,161.024983,135.053793,132.235803,183.602308
SE,NaN,109.900000,NaN,NaN,NaN,NaN,NaN,89.900000,NaN,NaN,...,119.900000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.900000,NaN
SP,173.252923,138.494849,129.618220,144.749245,126.800989,147.560788,122.646414,119.479391,124.316050,147.076048,...,117.929728,123.478835,146.307109,178.404232,134.135294,114.813803,122.401964,157.606238,108.791428,161.856989
sp,NaN,NaN,NaN,NaN,217.900000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129.400000,NaN

In [120]:
table.drop(['sp'], axis=0)

customer_state,AC,AL,AM,AP,BA,CE,DF,ES,GO,MA,...,PR,RJ,RN,RO,RR,RS,SC,SE,SP,TO
seller_state,,,,,,,,,,,,,,,,,,,,,
AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.000000,...,NaN,NaN,NaN,319.000000,NaN,NaN,NaN,94.000000,259.000000,NaN
BA,1270.000000,396.828333,1340.000000,813.450000,516.772373,413.315000,715.312143,338.288571,574.440909,648.130556,...,510.560000,419.939014,474.080000,1014.700000,850.000000,1001.080417,753.687500,520.985455,516.786923,179.000000
CE,NaN,214.000000,149.900000,NaN,155.880000,34.273333,234.098000,149.900000,NaN,599.000000,...,158.644000,480.362500,NaN,599.000000,NaN,NaN,311.000000,192.000000,176.800000,NaN
DF,199.000000,168.950000,NaN,NaN,149.546667,118.767692,130.555283,137.216087,120.644211,63.578000,...,141.087692,136.494444,172.800000,NaN,NaN,93.364762,123.476111,119.500000,110.318000,76.947500
ES,NaN,99.000000,NaN,NaN,158.810000,121.998571,152.933333,130.727273,129.333333,95.945000,...,101.290833,124.287368,18.900000,NaN,NaN,127.802917,102.592000,NaN,117.625977,220.000000
GO,86.995000,822.557778,52.900000,NaN,126.087778,127.101111,145.959091,157.832500,118.794348,137.358182,...,78.103889,89.153393,95.900000,108.390000,NaN,90.652143,95.515000,NaN,159.952612,98.500000
MG,195.950000,213.763333,156.744286,114.966667,105.817201,102.991589,129.881364,106.974118,121.332872,111.884096,...,118.975584,119.246501,128.173784,127.035909,42.930000,130.275687,104.020957,103.106410,111.127105,121.845652
MS,369.800000,NaN,NaN,NaN,189.900000,NaN,189.717500,NaN,261.990000,NaN,...,193.945000,191.310000,NaN,NaN,NaN,129.990000,174.900000,NaN,168.969412,NaN
MT,NaN,NaN,51.945000,NaN,133.580000,NaN,148.283333,168.325000,94.109000,138.633333,...,98.198750,154.966667,34.500000,69.612500,169.000000,135.425000,80.673333,NaN,136.551351,NaN
PA,NaN,NaN,NaN,NaN,339.000000,NaN,NaN,NaN,NaN,NaN,...,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,349.000000,137.125000,NaN
PB,NaN,747.250000,NaN,NaN,544.000000,624.745000,278.700000,NaN,NaN,67.900000,...,NaN,434.257143,159.000000,NaN,NaN,NaN,1899.000000,NaN,717.400000,699.500000
PE,34.990000,39.456000,NaN,NaN,53.924000,68.832500,39.900000,57.450000,316.615000,NaN,...,71.190000,77.866667,22.463333,NaN,NaN,612.131667,28.416667,40.000000,137.625833,NaN
PI,NaN,NaN,NaN,NaN,295.000000,295.000000,NaN,NaN,NaN,296.966667,...,NaN,295.000000,NaN,NaN,NaN,295.000000,295.000000,NaN,NaN,NaN
PR,54.450000,385.506545,141.973077,574.588000,202.419144,211.371594,165.624878,154.108088,224.088434,217.513250,...,142.875172,143.336318,224.998636,240.480000,190.280000,141.023437,137.527840,196.948125,144.867871,166.384500
RJ,NaN,123.809091,160.286000,55.000000,201.187377,212.914565,182.643735,160.571310,154.117907,144.288000,...,174.993960,153.444924,151.401176,162.693000,399.990000,158.185000,171.873854,120.860000,167.447222,141.008571
RN,NaN,94.900000,NaN,NaN,241.212500,210.966667,151.200000,NaN,NaN,NaN,...,799.000000,912.633333,33.560976,NaN,NaN,358.160000,NaN,NaN,93.233333,NaN
RO,NaN,NaN,NaN,NaN,279.990000,NaN,119.000000,228.000000,NaN,NaN,...,208.100000,693.323333,NaN,NaN,NaN,374.990000,NaN,NaN,439.480000,NaN
RS,69.945000,212.087778,158.450000,105.000000,237.271111,319.533500,180.753333,128.378485,256.248065,262.899231,...,160.441950,179.791992,76.355000,166.046667,NaN,174.088587,171.622500,334.087778,146.951723,359.323333
SC,337.192500,104.546364,114.912500,123.200000,235.725165,246.671304,120.065000,137.275800,256.566596,157.757059,...,137.684521,139.626853,187.726000,145.937143,NaN,155.476093,161.024983,135.053793,132.235803,183.602308
SE,NaN,109.900000,NaN,NaN,NaN,NaN,NaN,89.900000,NaN,NaN,...,119.900000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.900000,NaN
SP,173.252923,138.494849,129.618220,144.749245,126.800989,147.560788,122.646414,119.479391,124.316050,147.076048,...,117.929728,123.478835,146.307109,178.404232,134.135294,114.813803,122.401964,157.606238,108.791428,161.856989

In [135]:
dist = pd.read_csv('dist.csv', sep=';', index_col=0)

In [136]:
dist

,AC,AL,AM,AP,BA,CE,DF,ES,GO,MA,...,PR,RJ,RN,RO,RR,RS,SC,SE,SP,TO
AM,1149,0,1509,2765,2865,0,3291,0,761,0,...,2689,0,0,0,2689,0,0,2689,0,0
BA,4457,5009,1454,1126,839,5009,1643,0,4023,0,...,1453,0,0,0,1453,0,0,1453,0,0
CE,3300,2383,1300,435,1855,2383,1854,0,2855,0,...,2368,0,0,0,2368,0,0,2368,0,0
DF,2246,1932,620,1775,947,1932,173,0,1900,0,...,873,0,0,0,873,0,0,873,0,0
ES,4109,4476,2214,2178,0,4476,1428,0,3575,0,...,882,0,0,0,882,0,0,882,0,0
GO,2138,1912,724,1948,1022,1912,0,0,1813,0,...,810,0,0,0,810,0,0,810,0,0
MG,2786,2556,1178,1831,378,2556,666,0,2477,0,...,489,0,0,0,489,0,0,489,0,0
MS,1827,2013,1320,2654,1490,2013,705,0,1634,0,...,894,0,0,0,894,0,0,894,0,0
MT,1414,1453,1029,2524,1745,1453,740,0,1137,0,...,1326,0,0,0,1326,0,0,1326,0,0
PA,2333,1292,973,1550,2275,1292,1693,0,1886,0,...,2463,0,0,0,2463,0,0,2463,0,0
PB,3632,2819,1521,151,1581,2819,2442,0,3200,0,...,2216,0,0,0,2216,0,0,2216,0,0
PE,3618,5698,2058,297,1483,5698,2332,0,4712,0,...,2128,0,0,0,2128,0,0,2128,0,0
PI,4900,5267,1401,1171,1713,5267,1986,0,4366,0,...,2792,0,0,0,2792,0,0,2792,0,0
PR,2601,2734,1693,2645,1076,2734,972,0,2412,0,...,338,0,0,0,338,0,0,338,0,0
RJ,4007,4374,2124,2625,412,4374,1338,0,3473,0,...,357,0,0,0,357,0,0,357,0,0
RN,3616,5985,1527,0,1706,5985,2618,0,3179,0,...,2320,0,0,0,2320,0,0,2320,0,0
RO,449,901,0,4998,2835,901,2390,0,0,0,...,2463,0,0,0,2463,0,0,2463,0,0
RS,2814,4563,2747,4066,1536,4563,1847,0,2706,0,...,852,0,0,0,852,0,0,852,0,0
SC,2809,2981,1931,2802,1160,2981,1215,0,2641,0,...,489,0,0,0,489,0,0,489,0,0
SE,3359,2673,1235,604,1102,2673,1461,0,2946,0,...,1731,0,0,0,1731,0,0,1731,0,0
SP,3604,3971,1776,2947,741,3971,926,0,3070,0,...,0,0,0,0,0,0,0,0,0,0

In [137]:
table/dist

customer_state,AC,AL,AM,AP,BA,CE,DF,ES,GO,MA,...,PR,RJ,RN,RO,RR,RS,SC,SE,SP,TO
AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf,...,NaN,NaN,NaN,inf,NaN,NaN,NaN,0.034957,inf,NaN
BA,0.284945,0.079223,0.921596,0.722425,0.615938,0.082514,0.435370,inf,0.142789,inf,...,0.351383,inf,inf,inf,0.584997,inf,inf,0.358558,inf,inf
CE,NaN,0.089803,0.115308,NaN,0.084032,0.014382,0.126266,inf,NaN,inf,...,0.066995,inf,NaN,inf,NaN,NaN,inf,0.081081,inf,NaN
DF,0.088602,0.087448,NaN,NaN,0.157916,0.061474,0.754655,inf,0.063497,inf,...,0.161612,inf,inf,NaN,NaN,inf,inf,0.136884,inf,inf
ES,NaN,0.022118,NaN,NaN,inf,0.027256,0.107096,inf,0.036177,inf,...,0.114842,inf,inf,NaN,NaN,inf,inf,NaN,inf,inf
GO,0.040690,0.430208,0.073066,NaN,0.123374,0.066475,inf,inf,0.065524,inf,...,0.096425,inf,inf,inf,NaN,inf,inf,NaN,inf,inf
MG,0.070334,0.083632,0.133060,0.062789,0.279940,0.040294,0.195017,inf,0.048984,inf,...,0.243304,inf,inf,inf,0.087791,inf,inf,0.210852,inf,inf
MS,0.202408,NaN,NaN,NaN,0.127450,NaN,0.269103,NaN,0.160337,NaN,...,0.216941,inf,NaN,NaN,NaN,inf,inf,NaN,inf,NaN
MT,NaN,NaN,0.050481,NaN,0.076550,NaN,0.200383,inf,0.082770,inf,...,0.074056,inf,inf,inf,0.127451,inf,inf,NaN,inf,NaN
PA,NaN,NaN,NaN,NaN,0.149011,NaN,NaN,NaN,NaN,NaN,...,0.010150,NaN,NaN,NaN,NaN,NaN,NaN,0.141697,inf,NaN
PB,NaN,0.265076,NaN,NaN,0.344086,0.221619,0.114128,NaN,NaN,inf,...,NaN,inf,inf,NaN,NaN,NaN,inf,NaN,inf,inf
PE,0.009671,0.006925,NaN,NaN,0.036361,0.012080,0.017110,inf,0.067193,NaN,...,0.033454,inf,inf,NaN,NaN,inf,inf,0.018797,inf,NaN
PI,NaN,NaN,NaN,NaN,0.172212,0.056009,NaN,NaN,NaN,inf,...,NaN,inf,NaN,NaN,NaN,inf,inf,NaN,NaN,NaN
PR,0.020934,0.141005,0.083859,0.217236,0.188122,0.077312,0.170396,inf,0.092906,inf,...,0.422708,inf,inf,inf,0.562959,inf,inf,0.582687,inf,inf
RJ,NaN,0.028306,0.075464,0.020952,0.488319,0.048677,0.136505,inf,0.044376,inf,...,0.490179,inf,inf,inf,1.120420,inf,inf,0.338543,inf,inf
RN,NaN,0.015856,NaN,NaN,0.141391,0.035249,0.057754,NaN,NaN,NaN,...,0.344397,inf,inf,NaN,NaN,inf,NaN,NaN,inf,NaN
RO,NaN,NaN,NaN,NaN,0.098762,NaN,0.049791,inf,NaN,NaN,...,0.084490,inf,NaN,NaN,NaN,inf,NaN,NaN,inf,NaN
RS,0.024856,0.046480,0.057681,0.025824,0.154473,0.070027,0.097863,inf,0.094696,inf,...,0.188312,inf,inf,inf,NaN,inf,inf,0.392122,inf,inf
SC,0.120040,0.035071,0.059509,0.043969,0.203211,0.082748,0.098819,inf,0.097148,inf,...,0.281563,inf,inf,inf,NaN,inf,inf,0.276184,inf,inf
SE,NaN,0.041115,NaN,NaN,NaN,NaN,NaN,inf,NaN,NaN,...,0.069266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf,NaN
SP,0.048072,0.034877,0.072983,0.049117,0.171121,0.037160,0.132448,inf,0.040494,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
sp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [141]:
table.iloc[0,:]

customer_state
AC      NaN
AL      NaN
AM      NaN
AP      NaN
BA      NaN
CE      NaN
DF      NaN
ES      NaN
GO      NaN
MA    104.0
MG      NaN
MS      NaN
MT      NaN
PA      NaN
PB      NaN
PE      NaN
PI      NaN
PR      NaN
RJ      NaN
RN      NaN
RO    319.0
RR      NaN
RS      NaN
SC      NaN
SE     94.0
SP    259.0
TO      NaN
Name: AM, dtype: float64

In [149]:
table1 = []
for i in range(0,26):
    table1 = table1 + table.iloc[i,:].tolist()

IndexError: single positional indexer is out-of-bounds

In [151]:
table.[0].tolist()

SyntaxError: invalid syntax (<ipython-input-151-0a482e90746a>, line 1)

# 3- Definir a Hipótese

![Explo](img/what-if.jpg "Variables specification")

# 4- Corrigir os ruídos e Organizar o Dataset

> Drop, fillna, NumericalFeaturesImputer...

<br>
<center>
<img src="http://media.tumblr.com/tumblr_medmv9n8JL1ro2d43.gif" alt="drawing" width="500px"></center>

# 5- Avaliar a Hipótese

> Gráficos ou testes de hipóteses

<br>
<center>
<img src="https://media1.tenor.com/images/c109257362ef9924a11c64fd1b051f43/tenor.gif?itemid=5205898" alt="drawing" width="500px"></center>

# 6- Preparar e Apresentar os Resultados

<br>
<center>
<img src="https://i.imgur.com/CKyA2sd.gif" alt="drawing" width="500px"></center>